name: capstone-lab
dependencies:
- openssl=1.0.2j
- pip>=8.1.2
- psutil=5.4.7
- python>=3.6.2
- readline=7.0
- setuptools=27.2.0
- sqlite=3.20.1
- tk>=8.6
- wheel=0.32.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - appnope==0.1.0
  - h5py==2.8.0
  - cycler==0.10.0
  - decorator==4.0.10
  - entrypoints==0.2.2
  - ipykernel==5.1.0
  - ipython==7.1.1
  - ipython-genutils==0.2.0
  - ipywidgets==7.4.2
  - jinja2==2.8
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.2.3
  - jupyter-console==6.0.0
  - jupyter-core==4.4.0
  - keras==2.2.4
  - markupsafe==0.23
  - matplotlib==3.0.2
  - mistune==0.8.1
  - nbconvert==5.4.0
  - nbformat==4.4
  - notebook==5.7.0
  - numpy==1.15.2
  - pandas==0.23.2
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pillow==5.3.0
  - prompt-toolkit==2.0.7
  - protobuf==3.6.0
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.10
  - python-dateutil==2.5.3
  - pytz==2016.7
  - pyzmq==17
  - qtconsole==4.2.1
  - scikit-learn==0.20.0
  - scipy==0.18.1
  - seaborn==0.8.1
  - simplegeneric==0.8.1
  - six==1.10.0
  - statsmodels==0.9.0
  - tensorflow==1.11.0
  - Theano==1.0.3
  - terminado==0.8.1
  - tornado==4.4.2
  - tqdm==4.8.4
  - traitlets==4.3.1
  - wcwidth==0.1.7
  - widgetsnbextension==3.4.0
